### ISSUE TITLE
Support for named markdown images

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/markup-it#17]
See https://github.com/GitbookIO/gitbook/issues/1447

**Comment by simov** [comment]
I don't know if that could be of any help, but the [marked](https://github.com/chjj/marked) parser already supports that.

**Comment by SamyPesse** [comment]
Fixed by #16

**Comment by simov** [comment]
Excuse me but *named markdown images* refers to `
[![image-url]][image-link]` so the problem is that your parser does not support named image-link with image-url. I'm copy/pasting my other issue here:


---

Things like:

[![travis-ci]][travis]

  [travis-ci]: https://img.shields.io/travis/simov/purest/master.svg?style=flat-square (Build Status - Travis CI)
  [travis]: https://travis-ci.org/simov/purest

```md
[![travis-ci]][travis]

  [travis-ci]: https://img.shields.io/travis/simov/purest/master.svg?style=flat-square (Build Status - Travis CI)
  [travis]: https://travis-ci.org/simov/purest
```

As you can see this is rendered correctly in GitHub, the image above have a title and it can be clicked. This doesn't seem to work with latest GitBook:


```
CLI version: 2.3.0
GitBook version: 3.2.0
```

---

The PR you are referring to adds support for titles, but not support for named image-link. So I suggest you re-open this issue.

**Comment by SamyPesse** [comment]
Sorry!
